### ISSUE TITLE
PR to base16-builder

### ISSUE THREAD

**Issue by aleprovencio** [dawikur/base16-gruvbox-scheme#2]
This is great, good work!
Maybe you should make a PR to add this scheme to base16 repo?

**Comment by dawikur** [comment]
You mean this one https://github.com/chriskempson/base16?

**Comment by aleprovencio** [comment]
sorry about late response, maybe this one is better https://github.com/base16-builder/base16-builder

**Comment by dawikur** [comment]
I will take a look. Thanks

**Comment by dawikur** [comment]
Sorry this took so long, but PR is now a thing :smile: 
base16-builder/base16-builder#166

**Comment by aleprovencio** [comment]
that's great thank you

**Comment by dawikur** [comment]
OK, Closing this one.
