### ISSUE TITLE
Red is too... Red?

### ISSUE THREAD

**Issue by andreyorst** [dawikur/base16-gruvbox-scheme#3]
Files with lots of red-colored syntax elements is hard to read.
![image](https://user-images.githubusercontent.com/19470159/38255056-81506c74-3763-11e8-9b92-d7ac59ddfbe9.png)

**Comment by dawikur** [comment]
Hi @andreyorst, sorry for quite some delay with response :)

_red_ is in [base16's base08](https://github.com/dawikur/base16-gruvbox-scheme/blob/master/gruvbox-light-medium.yaml#L11) color, which is described by [styling guides](https://github.com/chriskempson/base16/blob/master/styling.md) as 

> **base08** - Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted

for me this _Diff Deleted_ implies it has to be redish.

After this, it is up to [base16-vim](https://github.com/chriskempson/base16-vim) how it will 
be used in the actual highliting.

For VimL e.g. **let** sounds like a keyword ;-), and **base0E** should be used
> **base0E** - Keywords, Storage, Selector, Markup Italic, Diff Changed
something around purple :)

You can use
```vimL
:highlight Keyword
```
to check what it is.

In my case **Keyword** is _puple_-ish and I see a lot of red when using
base16-gruvbox-dark-*

So, the _redish_ from your example comes from **vim.vim** syntax file from the vim itself
> syn keyword»vimLet    let    unl[et]»skipwhite nextgroup=vimVar,vimFuncVar
> hi def link vimCommand    Statement
> hi def link vimLet    vimCommand
> hi def link vimVar    Identifier

and [in base16-vim](https://github.com/chriskempson/base16-vim/blob/master/colors/base16-gruvbox-dark-medium.vim) we have
> call <sid>hi("Statement",    s:gui08, "", s:cterm08, "", "", "")
> call <sid>hi("Identifier",   s:gui08, "", s:cterm08, "", "none", "")

So basically you vim-syntax file describes those elements differently, but
base16-vim both binds to **base08** color.

Not sure than how this can be 'fixed' the best way.

* we could add another overloads to **base16-gruvbox**, but this is rather not the best place for changes
* you could raise in [base16-vim](https://github.com/chriskempson/base16-vim/blob/master/colors/base16-gruvbox-dark-medium.vim#L224) issue to change how **Statement** is is highlihted
* you could go to vim maintainers and try to force to syntax highlighting  for statements ;)
* or simply redefine few color binding, e.g. Statement (but it will be probably whole in one color)

Does this all makes sense? 

Edit:
Or do you only say that red is incorrect?
Well, [gruvbox](https://github.com/morhetz/gruvbox) defines 2 versions of colors,
I had arbitrarily used the one which gives more contrast. I can add another set
of overloads with the second color version.
